language: c

env:
    global:
        - PDVERSION='0.47-1'

matrix:
    include:
        - env: PLATFORM='linux64'
          os: linux
          dist: trusty
          sudo: required
          compiler: gcc

        - env: PLATFORM='linux32'
          os: linux
          dist: trusty
          sudo: required
          compiler: gcc

        - env: PLATFORM='osx'
          os: osx

        - env: PLATFORM='windows'
          os: linux
          dist: trusty
          sudo: required
          compiler: gcc

before_install: bash ./travis-build/${PLATFORM}_before_install.sh
script: bash ./travis-build/${PLATFORM}_script.sh
after_success:
    - bash ./travis-build/${PLATFORM}_pack.sh
    - bash ./travis-build/upload.sh
