language: c

env:
    global:
        - PDVERSION='0.48-1'
        - secure: "DA85V8jBW8C6n6z9qiGufU1BK1atVUsvnceHIuf0pG64faZBNLg93J3SfyV2/NN0C4AVAaVHSM+F8XR8Ba8GdxHbW8OGJR+vcgr6ZFg5Qai/xmMJm5MfcR/oPFj8nuMnT61rb6Jm5QpuURRwAjio+x7wCHQJkkpH1TiQF9mV2Tk="

matrix:
    include:
        - env: PLATFORM='linux64'
          os: linux
          dist: trusty
          sudo: required
          compiler: gcc

        - env: 
          - PLATFORM='linux32'
          - DIST=stretch
          - DEBIAN_ARCH=i386
          - CHROOTDIR=/opt/crosscompilation

          os: linux
          dist: trusty
          sudo: required
          compiler: gcc

        - env: 
          - PLATFORM='linux_arm'
          - DIST=stretch
          - DEBIAN_ARCH=armhf
          - CHROOTDIR=/opt/crosscompilation

          os: linux
          dist: trusty
          sudo: required
          compiler: gcc

        - env: PLATFORM='osx'
          os: osx

        - env: 
          - PLATFORM='windows'
          - MXE_TARGET=i686-w64-mingw32.static
          - MXE_PATH_SLUG=i686-w64-mingw32.static
          - PD_UNZIP_PATH=pd
          - PD_DIR=/tmp/pd
          - PD_URL=http://msp.ucsd.edu/Software/pd-${PDVERSION}.msw.zip
          - MACHINE=i386
          - CUSTOM_CFLAGS='-march=core2 -mfpmath=sse -msse -msse2 -msse3'

          os: linux
          dist: trusty
          sudo: required
          compiler: gcc

        - env: 
          - PLATFORM='windows64'
          - MXE_TARGET=x86-64-w64-mingw32.static
          - MXE_PATH_SLUG=x86_64-w64-mingw32.static
          - PD_UNZIP_PATH=pd-0.48-1test2-ia64
          - PD_DIR=/tmp/pd
          - PD_URL=http://msp.ucsd.edu/Software/${PD_UNZIP_PATH}.msw.zip
          - MACHINE=x86_64
          - CUSTOM_CFLAGS='-march=core2 -mfpmath=sse -msse -msse2 -msse3'

          os: linux
          dist: trusty
          sudo: required
          compiler: gcc

before_install: bash ./travis-build/${PLATFORM}_before_install.sh
script: bash ./travis-build/${PLATFORM}_script.sh
after_success: bash ./travis-build/${PLATFORM}_pack.sh
deploy:
    skip_cleanup: true
    provider: script
    script: bash ./travis-build/upload.sh
    on: 
        all_branches: true
